### ISSUE TITLE
dmenu-i3-window-jumper does not work with i3 bindsym

### ISSUE THREAD

**Issue by georgeabr** [minos-org/minos-tools#2]
dmenu-i3-window-jumper does not work with i3 bindsym, but works when launched from terminal.

I have this in my i3 config file.
`bindsym $mod+space exec "/home/george/./dmenu-i3-window-jumper1.sh"`
When I press `Mod+space` - which is mapped to `Winkey+space`, nothing happens.

But rofi works with the same shortcuts:
`bindsym $mod+space exec "rofi -modi window -show window"`

What am I doing wrong?

**Comment by javier-lopez** [comment]
I suspect the path to the script could be incorrect, but to debug you could use:

`bindsym $mod+space exec "/home/george/./dmenu-i3-window-jumper1.sh &> /tmp/out"`

If the script itself is incorrect and you dont mind generating a full backtrace, you may want to use:

`bindsym $mod+space exec "bash -x /home/george/./dmenu-i3-window-jumper1.sh &> /tmp/out"`

And review `/tmp/out` for additional hints

**Comment by georgeabr** [comment]
Below is the output from the script, when ran as per your instructions, @javier-lopez .
Nothing shows on-screen, when bindsym key is triggered.
```
++ expr /home/george/./dmenu-i3-window-jumper.sh : '.*/\([^/]*\)'
+ progname=dmenu-i3-window-jumper.sh
+ '[' '!' -t 0 ']'
++ cat
```
Can you advise on next steps? Thanks.

**Comment by javier-lopez** [comment]
Could you remove https://github.com/minos-org/minos-desktop-tools/blob/master/tools/dmenu-launcher#L379-L382 these lines and see if that helps?

**Comment by georgeabr** [comment]
Thanks for the suggestion, @javier-lopez, it works.
I really appreciate your quick help.

**Comment by javier-lopez** [comment]
No problem @georgeabr , I'll close this report and leave it as a reference, if more persons get into this problem I'll consider removing such lines from the script
